service: psycopg2-lambda-layer

provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  profile: kbs-iam

layers:
  psycopg2-py37:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.7
    retain: true
